### ISSUE TITLE
Unable to rebuild without external data

### ISSUE THREAD

**Issue by jdlangs** [JuliaCI/pkg.julialang.org#24]
Hi Iain, I've forked this repo and want to test out making some small changes. However, I cannot regenerate the html because I don't have access to the raw json data from the package evaluator. Are those files available somewhere? In `pulljson.sh` it looks like you would download them off your personal server, but now that's commented out?

**Comment by IainNZ** [comment]
Hi @phobon, the issue is the machine had to be moved and is now in my house (!) hence the local IP. We're hoping to get some more permanent infrastructure through MIT, but for now this is all we've got. I'm not even in Cambridge right now so I don't have access to the machine. Not an ideal situation!

**Comment by jdlangs** [comment]
Ouch, well hopefully something gets sorted out. Then for now I'll either test with fake data or try to get the evaluator running locally.

I guess this issue should stay open until the data files are publicly visible?

**Comment by IainNZ** [comment]
I guess it can, yeah.

**Comment by IainNZ** [comment]
I'm not sure the raw data is ever going to be publicly available, as it would require a place to host it and its too large to be shoving onto git every day. I think the best option is just runnign locally, maybe on a subset.
